### ISSUE TITLE
Windows exrm release bat does not work in directories with spaces

### ISSUE THREAD

**Issue by fire** [bitwalker/exrm#260] opened 2015-12-03 06:14 UTC
running bin/bgfx.bat console

```
The system cannot find the file specified.
Error occurred while processing: C:\Users\My.
The system cannot find the path specified.
"Using C:\Users\My Name\Downloads\ex_bgfx\releases\\bgfx.bat"
'"C:\Users\My Name\Downloads\ex_bgfx\releases\\bgfx.bat"' is not recognized as an internal or external command, operable program or batch file.
```

Expected that the bat will work in directories with spaces.

**Comment by bitwalker** [comment] 2015-12-04 02:38
@fire Work is ongoing to bring the batch file up to par, including a fix for this specific issue. I'll keep this open until it's merged into master.

**Comment by fire** [comment] 2016-03-06 16:42
Status check?

**Comment by Gyllsdorff** [comment] 2016-03-07 19:00
It does not work in the latest release. The problem is that "bin/[APP].bat" and "release/[VERSION]/[APP].bat" sometimes use quotes around the paths, sometimes forgets the quotes and some paths gets double quoted.

I had to do the following to get the `console` command to work.

In "bin/[APP].bat": 
line 19, `@for /f "delims=" %%i in ('type "%start_erl%"') do @(` 
Add quotes around `%start_erl%`.

in "release/[VERSION]/[APP].bat":
line 29, `@for /f "delims=" %%i in ('type "%start_erl%"') do @(` 
Add quotes around `%start_erl%`.

line 130, `@set conform_schema=%rel_dir%\%rel_name%.schema.exs` 
Remove the quotes around `%rel_dir%\%rel_name%.schema.exs`. The script correctly puts quotes around `conform_schema` on line 143 and 144 which means you end up with `if ""[path]"" (`. 

line 203, `@start "%rel_name% console" "%werl%" -config "%sys_config%" ^` 
Add quotes around `%werl%`.

I can submit a pull request with the rest of the fixes sometimes next week if you want.

**Comment by fire** [comment] 2016-03-07 21:33
That would be great, and I can play with it.

**Comment by bitwalker** [comment] 2016-03-08 16:49
@Gyllsdorff If you can submit a PR that would be greatly appreciated!

@fire There are a few people working on various Windows-related PRs right now, so things are improving, but still not ready for prime-time sadly. I plan to announce when Windows support is legit, so that people are aware, in the meantime though, I throw the windows label on anything related to it in the issue tracker

**Closed** 2018-04-06 22:32 UTC
Labels: deployment/operating-system, windows
