### ISSUE TITLE
Upgrade fails with "eaddrinuse"

### ISSUE THREAD

**Issue by bencates** [bitwalker/exrm#272] opened 2016-01-05 22:42 UTC
Not sure if this is the correct place to report this, but I'm hoping you can at least point me in the right direction.

I'm trying to perform an upgrade on my Phoenix API application (from 1.0.4 to 1.1.0) and my deploy script is breaking.

```
1 ubuntu@server-06:/var/www/hal-staging⟫ bin/hal upgrade "0.1.0-rc2"
Using /var/www/hal-staging/releases/0.0.8/hal.sh
Release 0.1.0-rc2 is already unpacked, now installing.
Generating vm.args/sys.config for upgrade...
sys.config ready!
vm.args ready!
Release 0.1.0-rc2 is already unpacked, now installing.
escript: exception error: no case clause matching 
                 {error,
                     {code_change_failed,<7096.1159.0>,ranch_acceptors_sup,
                         189618188339335720598124329776893318811,
                         {'EXIT',
                             {listen_error,'Elixir.Hal.Endpoint.HTTP',
                                 eaddrinuse}}}}
```

The error confuses me because the address is **supposed** to be in use; it's the port that the old version was using.
# 

Tangentially related, I can't seem to upgrade while the app is not running.  The first thing I tried to debug (since this isn't in production yet) was stop the app, do a cold upgrade, then restart it.  Running `bin/hal upgrade $VERSION` while the app is shut down echoes the "Using ..." line, but does nothing else.

Is it possible to perform a cold version swap, and if not would you please consider adding a more useful error message?

**Comment by bitwalker** [comment] 2016-01-08 16:01
You only need to run `upgrade` on a live system. An "upgrade" of a stopped system is simply deploying the release over the top of the old one, as that is more or less what "upgrade" does (ignoring all the things it does to perform the code change). There should have been an error when running `upgrade` while the node is down, saying basically that, but if not, then it's definitely something that should be fixed.

As far as the error you got: I'm not sure I can troubleshoot effectively without access to the source, but the important thing to look at would be what code changed between the old version and the new one. It looks to me like the `code_change` callback is trying to setup the HTTP listener as if starting for the first time, which would fail because the old version of the module does not go away until `code_change` completes successfully, and any in-flight requests are done being processed. A code change of a module with a socket as part of it's state needs to pass that socket on to the new version of the module so that the connection is never dropped. By default, `code_change` passes the old state to the new module, so the thing to check would be whether or not the `code_change` callback was implemented, and if so, is it forgetting to handle some of the old module's state?

**Comment by aaronjensen** [comment] 2016-02-01 20:19
The issue here is that cowboy/ranch can not actually be hot upgraded.

@bitwalker what would you recommend in this case aside from manually doing a non-hot deploy? Is there a way for us to detect this so that we can always do the same thing in an automated way? i.e. attempt an upgrade, and if it fails with this particular error, do a stop/start?  Thanks!

**Comment by bitwalker** [comment] 2016-02-18 19:39
@aaronjensen Sorry I didn't respond earlier, I've had a hard time keeping up with my open source projects lately due to work.

I'm suspicious why your app in particular is having this problem, as there are a number of Phoenix apps using releases that have not reported this issue (yet, anyway). But to answer your question, the boot script will return a non-zero exit code if a command fails, so if you were going to automate a fallback for deploys, you could check that the upgrade exits cleanly, and if not, run stop, extract the release tarball over the top of the deploy directory, then run start. You'd want to test that by inserting a `exit 1` in the upgrade command handler in the boot script just prior to executing the `install_upgrade` command to simulate the upgrade installation failing.

The downside of this approach is that you can't know why the upgrade failed using just the exit code, and you may not want to restart without knowing the why. You could parse the output of the upgrade command looking for the specific failure you are willing to automate away, but I'm not sure it's a good idea to automate it completely - my personal view is that if an upgrade fails, only a manual step is good enough to verify that the failure is truly spurious, ignoring the failure and installing the release anyway regardless of the error is a good way to cause yourself pain.

My real recommendation would be to isolate why that particular issue is happening (and I'm willing to help with that), so that it can be documented and you can rely on upgrades to be reliable. Once you start ignoring unexplained failures, it's a slippery slope, and at that point, you might as well just always do rolling restarts instead of hot upgrades.

**Comment by aaronjensen** [comment] 2016-02-23 04:35
@bitwalker it's not just my app, it looks to be @bencates' as well. I've also asked about it in #elixir-lang and gotten similar responses--cowboy/ranch cannot be upgraded. They said it is akin to trying to hot upgrade nginx, you just can't/don't do it.

At this point, we're leaning towards rolling upgrades as there have been too many gotchas with hot upgrades and much of the community is saying to shy away from them unless you absolutely need them.

**Comment by bitwalker** [comment] 2016-02-29 01:54
@aaronjensen I'm not sure what they mean about not being able to hot upgrade cowboy/ranch - I literally did exactly that in my ElixirConf talk in October.

In any case, the recommendation to not use hot upgrades unless you have a reason to use them is wise - if you can do no-downtime rolling releases, then there isn't much benefit to doing hot upgrades, or if you can simply afford to have downtime, then hot upgrades aren't worth the additional complexity. But they aren't magical, and they aren't that difficult, so it's not something to be scared of either.

**Comment by aaronjensen** [comment] 2016-02-29 03:36
@bitwalker interesting. I think what they mean is what the OP is talking about. It is the same thing I got--the address is in use. Maybe you work around this in your talk, I'll take a look.

**Comment by aaronjensen** [comment] 2016-02-29 03:39
Just to be clear, you are talking about upgrading the cowboy or ranch dependency itself, not applying an upgrade to an app that depends on them, correct?

**Comment by aaronjensen** [comment] 2016-03-04 06:33
@bitwalker just watched your talk, for a second time apparently, I remembered half way through I'd seen it :smile: So in your talk you did upgrade an app that used cowboy/ranch, but you did not upgrade cowboy/ranch itself, which is what this thread is about and the only time you get an EADDRINUSE from what i've seen. Any ideas how to work around this? #elixir-lang's suggestion was to just do a rolling upgrade if you need to upgrade cowboy/ranch.

**Comment by bitwalker** [comment] 2016-03-08 17:19
@aaronjensen Yes, I realized afterwards that I completely misunderstood. The issue is that the current version of cowboy (and probably ranch too) used by Phoenix, do not hold the connection in a process which handles the `system_code_change` callback (which is what is called in non-gen_server processes). It looks like Cowboy master *does* do so, but is not ready for primetime yet.

Forking Cowboy/Ranch, and adding `system_code_change` to the module holding the connection *should* allow you to do hot reloads. I am dying to try this, but am too swamped at the moment to do so. You can look at Cowboy master branch to see how it's being done.

Obviously the easy way is to just do rolling upgrades as suggested, when cowboy/ranch are being updated - and if you don't really need hot upgrades, it's probably better to stick to rolling upgrades. That said, working out these kinks is good for everyone, so if you've got a little time to play with it, making the modification I suggested is probably well worth the investment.

**Closed** 2018-04-06 22:32 UTC
