### ISSUE TITLE
exrm revert back to the previous version after stoping running of the server.

### ISSUE THREAD

**Issue by blisscs** [bitwalker/exrm#168] opened 2015-07-20 09:13 UTC
I have some issues upgrading the release using exrm when using with phoenixframework. The issue is when after stoping the running release. the upgrades changes revert back to the initial release when restarting it again.

Please refer to using exrm with phoenix here. http://www.phoenixframework.org/docs/advanced-deployment
Exrm version that I am using is this one {:exrm, "~> 0.15.3"}
To Reproduce -
After releasing the version 0.0.1 using mix release for the first time.

Let the production run using $ rel/test_app/bin/test_app start

then Do some changes and change the version number to 0.0.2 and do the mix release to get the version 0.0.2 out.

Then do the upgrade using $ rel/test_app/bin/test_app upgrade "0.0.2"

Everyhing is working fine until here.
When I stop the server using $ rel/test_app/bin/test_app stop

When I start the server again it came back to version "0.0.1" again.

**Comment by chawladev** [comment] 2015-07-20 09:48
I found out the issues here.

The issue is that when using $ rel/app_name/bin/app_name upgrade "0.0.2" it doesn't update the value of REL_VSN from "0.0.1" to "0.0.2" in the $ rel/app_name/bin/app_name file

So to fix this just open the file rel/app_name/bin/app_name and find the line with REL_VSN="0.0.1" and then update to REL_VSN="0.0.2" will fix this.

I am not sure is this the way of fixing this. Do we have to update the value of REL_VSN to the new version every time we do upgrade

**Comment by gjaldon** [comment] 2015-07-20 10:17
Cool @chawladev, that's helpful!

**Comment by bitwalker** [comment] 2015-08-12 16:14
Fixed in 0615313, released as 0.18.7

**Closed by bitwalker** 2015-08-12 16:14 UTC
