### ISSUE TITLE
remote_console does not work with OTP 19

### ISSUE THREAD

**Issue by manukall** [bitwalker/exrm#377] opened 2016-07-20 13:23 UTC
After upgrading to OTP 19, `remote_console` stopped working and outputs the following: 

```
{error_logger,{{2016,7,20},{15,20,43}},"~s~n",["beam/beam_load.c(1486): Error loading module binary:\n  there are local calls to the stub for the BIF binary:split/3\n"]}
{error_logger,{{2016,7,20},{15,20,43}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,{'EXIT',{undef,[{binary,module_info,[module],[]},{code,'-load_code_server_prerequisites/0-lc$^0/1-0-',1,[{file,"code.erl"},{line,369}]},{code,load_code_server_prerequisites,0,[{file,"code.erl"},{line,369}]},{code,do_start,1,[{file,"code.erl"},{line,325}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,343}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,326}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,292}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]}]}}},{offender,[{pid,undefined},{id,code_server},{mfargs,{code,start_link,[]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}
{error_logger,{{2016,7,20},{15,20,43}},crash_report,[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.33.0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,code_server,{'EXIT',{undef,[{binary,module_info,[module],[]},{code,'-load_code_server_prerequisites/0-lc$^0/1-0-',1,[{file,"code.erl"},{line,369}]},{code,load_code_server_prerequisites,0,[{file,"code.erl"},{line,369}]},{code,do_start,1,[{file,"code.erl"},{line,325}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,343}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,326}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,292}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]}]}}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,134}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}},{ancestors,[<0.32.0>]},{messages,[{'EXIT',<0.34.0>,normal}]},{links,[<0.32.0>,<0.31.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,987},{stack_size,27},{reductions,224}],[]]}
{error_logger,{{2016,7,20},{15,20,43}},std_info,[{application,kernel},{exited,{{shutdown,{failed_to_start_child,code_server,{'EXIT',{undef,[{binary,module_info,[module],[]},{code,'-load_code_server_prerequisites/0-lc$^0/1-0-',1,[{file,"code.erl"},{line,369}]},{code,load_code_server_prerequisites,0,[{file,"code.erl"},{line,369}]},{code,do_start,1,[{file,"code.erl"},{line,325}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,343}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,326}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,292}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]}]}}}},{kernel,start,[normal,[]]}}},{type,permanent}]}
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,code_server,{'EXIT',{undef,[{binary,module_info,[module],[]},{code,'-load_code_server_prerequisites/0-lc$^0/1-0-',1,[{file,\"code.erl\"},{line,369}]},{code,load_code_server_prerequisites,0,[{file,\"code.erl\"},{line,369}]},{code,do_start,1,[{file,\"code.erl\"},{line,325}]},{supervisor,do_start_child,2,[{file,\"supervisor.erl\"},{line,343}]},{supervisor,start_children,3,[{file,\"supervisor.erl\"},{line,326}]},{supervisor,init_children,2,[{file,\"supervisor.erl\"},{line,292}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,328}]}]}}}},{kernel,start,[normal,[]]}}}"}

Crash dump is being written to: erl_crash.dump...done
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,code_server,{'EXIT',{undef,[{binary,module_info,[module],[]},{code,'-load_code_serve
```

Commands like `start`, `attach`, `ping` still work and the node runs fine, too.

**Comment by bitwalker** [comment] 2016-07-21 21:15
Duplicate of the issue reported in #369. This is caused by BEAMs compiled by the earlier version of Erlang being included on the code path of the release. I'm looking into how be more precise about this, but currently the solution is to blow away the release `lib` directory and redeploy the latest version, so that the old BEAMs are no longer loaded.

**Comment by manukall** [comment] 2016-07-29 06:24
thanks! deleting everything (including the rel folder on the build host) indeed solved this.

**Closed** 2018-04-06 22:32 UTC
Labels: bug, deployment/general, duplicate
