### ISSUE TITLE
Upgrade fails when using short names

### ISSUE THREAD

**Issue by hexedpackets** [bitwalker/exrm#94] opened 2015-01-08 19:54 UTC
In my vm.args file, I've defined `-sname dealer`. Everything works fine when starting up:

    $ bin/router start
    $ bin/router ping
    pong

But attempting to upgrade fails and appears to be incorrectly expecting a FQDN:

    $ bin/router upgrade 0.0.2
    Node 'dealer@utility-dev' not responding to pings.

    =ERROR REPORT==== 8-Jan-2015::19:47:35 ===
    ** System running to use fully qualified hostnames **
    ** Hostname utility-dev is illegal **

The vm.args file for 0.0.2 is identical to the one for 0.0.1.

**Comment by bitwalker** [comment] 2015-01-08 20:32
You can define both a short and a long name, and use them interchangeably, so I would do that, rather than only defining a short name. The issue here appears to be that the escript which installs the upgrade requires the full name. Could you try defining a long name in addition to the short name and try again?

**Comment by hexedpackets** [comment] 2015-01-08 21:43
Providing both causes a new error when I try to ping it:

    $ bin/router ping
    escript: exception error: no function clause matching
                 erlang:set_cookie(nonode@nohost,mycookie)

I tried starting iex with both a short and long name set, and the long name seems to just get ignored. Trying to connect using the long name throws `** System NOT running to use fully qualified hostnames **`. Am I missing something?

**Comment by bitwalker** [comment] 2015-01-10 00:14
I'm sorry, I was mistaken about the ability to use both at the same time. I just read back through the shell code for booting the release and reviewed the Erlang docs and it's one or the other.  However I think the issue is different than what I thought. I'm wondering if you can tell me the result of `Node.self` when you run `bin/router console`. It should be `:"dealer@utility-dev"`, based on the original error message. If it's not, then we need to figure out why the VM is being given a different hostname than that expected by the boot script.

**Comment by hexedpackets** [comment] 2015-01-15 20:11
Yes, Node.self is `:"dealer@utility-dev"`. I've also noticed that with an sname `router stop` fails to stop the application, while it works with a long name. Not sure if this is actually related but it seems likely.

**Comment by bitwalker** [comment] 2015-01-16 18:44
Somehow I missed the error message which said `hostname utility-dev is illegal`. I'm at work, so I'll have to check when I get home, but I wonder if a qualified hostname would work, i.e. `utility-dev.local`. I'll see if I can reproduce it by playing around in a VM. Running `exrm-test` locally on my mac gets `:"test@127.0.0.1"` instead of a proper hostname.

**Comment by bitwalker** [comment] 2015-08-12 22:05
This is now fixed and will be released on hex soon.

**Closed** 2015-08-12 22:04 UTC
Labels: bug, deployment/appups
