### ISSUE TITLE
deps that are included listed as not included

### ISSUE THREAD

**Issue by antipax** [bitwalker/exrm#252] opened 2015-11-23 17:00 UTC
Getting this message with latest master when releasing:

```
Building release with MIX_ENV=prod.

You have dependencies (direct/transitive) which are not in :applications!
The following apps should to be added to :applications in mix.exs:

        ex_statsd => ex_statsd is missing from turbo
        pipe      => pipe is missing from turbo
        quantum   => quantum is missing from turbo
        murmur    => murmur is missing from turbo

Continue anyway? Your release may not work as expected if these dependencies are required! [Yn]:
```
ex_statsd is in my applications list for sure, as are pipe and murmur. ex_statsd defines an OTP app, but pipe and murmur do not. quantum is in my included_applications, and does define an OTP app. Pretty sure the error message is incorrect?

**Comment by antipax** [comment] 2015-11-23 17:31
Also, I should mention that when I agree to the warning, the release fails without an error message and no rel/<app> dir is created.

**Comment by bitwalker** [comment] 2015-11-23 18:08
@antipax An important thing to remember is that regardless of whether an application is an OTP app or just a library application (Timex for example), they still should be included in the applications list, as they are both still applications, the only difference being that an OTP app will be loaded/started whereas a library application will just be loaded since there is nothing to start.

Are all of those listed above direct dependencies? Are they hex, git, or path dependencies? It looks like there is a bug in the logic around determining whether an application was correctly included, but if you have a way for me to reproduce this, I can figure out where it's going wrong.

The feature is still experimental, so sorry for the trouble :(. I'm hoping to stabilize it before I release 1.0 proper.

**Comment by antipax** [comment] 2015-11-23 18:10
Yeah, thanks for the tip but I was aware and they are in the applications list. They're all direct hex dependencies.

**Comment by bitwalker** [comment] 2015-11-23 19:15
@antipax Ok I'll take a look today at some point and get a fix pushed up.

**Comment by antipax** [comment] 2015-11-23 19:16
@bitwalker Thanks!

**Comment by imsearchdev** [comment] 2015-11-25 04:15
We were able to re-produce this bug as well.  Using porcelain ~> 2.0.0 with an exrm version > 0.19.9 is enough to reproduce this.  All the 1.0.0-rc versions (3,4,5) fail with this bug.  Let us know if we can help test this in any way.  This fix for right now seems to be to use 0.19.9.

**Comment by bitwalker** [comment] 2015-11-25 15:34
@imsearchdev It shouldn't actually prevent you from building a release in any way, as it's always just a warning, it just happens to be the case that the warning is incorrect at the moment.

@antipax @imsearchdev If you build the release with --verbosity=verbose, do you see an error?

**Comment by imsearchdev** [comment] 2015-11-25 16:09
Oh, it very much prevented us from building a release for SOME of our projects.  It kept going after we told it to proceed, but after putting about 4 files in the rel directory it stopped.  We've reverted everything back to 0.19.9 for now so this is not a show stopper. 

Let us know if we can help test anything.

Thanks.

**Comment by antipax** [comment] 2015-11-25 16:32
@bitwalker no error when building on latest master with --verbosity=verbose, and the release actually appears to be generated properly. Not sure what was going on before, but it was the same behavior @imsearchdev describes where 4 files are created in a sub-dir of the rel directory and then it stopped.

**Comment by bitwalker** [comment] 2015-11-25 17:27
@imsearchdev That sounds like a separate issue, because that warning in no way affects the release, it literally just builds a list of paths to deps which it thinks should be added to the applications list and then prints a warning with a confirmation message. If your release failed, it was definitely not due to that. You'd need to run with `--verbosity=verbose` to know what caused it to fail unexpectedly.

@imsearchdev @antipax This sounds like it might be due to a bug I fixed yesterday, where on some platforms the answer to the confirmation message contained a newline, but the code which checks the answer and decides whether to abort or continue wasn't handling that case, so it just aborted with no message. I suspect the 4 files which are created are the config files exrm uses while building, but I'd have to see a file listing to tell you for sure. @imsearchdev You might want to try master then to see if you can reproduce that issue with that fix in place.

**Comment by bitwalker** [comment] 2015-11-27 17:45
The issue with applications being listed as missing when they are included in the top-level `mix.exs` is fixed in master. I should have a new release out today.

**Closed by bitwalker** 2015-11-27 17:45 UTC
