### ISSUE TITLE
can't ping running app

### ISSUE THREAD

**Issue by schurig** [bitwalker/exrm#341] opened 2016-04-26 08:25 UTC
With `exrm 1.0.3` I can't ping my app anymore.
`Node myapp@www1 not responding to pings.`

I found out that with the previous exrm version the generated `running-config/vm.args` file was different:

**before**
```
## Name of the node
-name myapp@127.0.0.1

## Cookie for distributed erlang
-setcookie myapp
...
...
```

**now**
```
## Name of the node
-sname myapp

## Cookie for distributed erlang
-setcookie myapp
...
...
```

So I tried to use the old config but it says:

````
Can't set short node name!
Please check your configuration
escript: exception error: no match of right hand side value
                 {error,
                     {{shutdown,
                          {failed_to_start_child,net_kernel,
                              {'EXIT',nodistribution}}},
                      {child,undefined,net_sup_dynamic,
                          {erl_distribution,start_link,
                              [['myapp_maint_2430@127.0.0.1',
                                shortnames]]},
                          permanent,1000,supervisor,
                          [erl_distribution]}}}
````
when I run `bin/myapp ping`

Any idea what is going on?

**Comment by daisuke-morita** [comment] 2016-04-26 08:56
I encountered the same problem. It appears to be caused by the difference of relx version:

https://github.com/erlware/relx/commit/026f42bc111362354c7de8ee5eb0645c104d448f

While I couldn't figure out why ping won't work for short name, I worked around it by putting rel/vm.args to override the default.

**Comment by schurig** [comment] 2016-04-26 09:03
@daisuke-morita I'm glad that I'm not the only one who ran into this.. Thanks for your answer!

Just to be clear, you created the `/priv/vm.args` file with the following options?

````
## Name of the node
-name myapp@127.0.0.1

## Cookie for distributed erlang
-setcookie myapp
```

**Comment by daisuke-morita** [comment] 2016-04-26 09:10
I created the `rel/vm.args` file with options just like you wrote.

https://github.com/bitwalker/exrm/blob/master/docs/Release%20Configuration.md

**Comment by schurig** [comment] 2016-04-26 09:34
@daisuke-morita thanks, it works for me

**Comment by midas** [comment] 2016-05-23 04:29
@bitwalker This is definitely an issue that eventually will effect all users of exrm.  Is there something that can be done on the exrm side that can fix this issue?

**Comment by bitwalker** [comment] 2016-05-24 02:29
@midas Yeah I can template out vm.args as well, rather than using the same one from relx, since we're already doing that for most everything anyway. I'm not sure why that change was made, since I would think the full name would be a better default.

**Comment by midas** [comment] 2016-05-24 03:21
@bitwalker I would like to take a stab at this.  Please assign it to me when you can.  Thanks!

**Comment by bitwalker** [comment] 2016-05-24 16:04
@midas Sorry man, got to it before I saw you comment, let me know if there are others you are interested in tackling!

**Closed** 2016-05-24 16:03 UTC
Labels: bug, deployment/general, third party issue
