### ISSUE TITLE
undefined function when generating release

### ISSUE THREAD

**Issue by cjimison** [bitwalker/exrm#248] opened 2015-11-19 19:42 UTC
Hi bitwalker,

When I pull  the latest code I am getting a strange error when generating a release:

Building release with MIX_ENV=dev.
** (UndefinedFunctionError) undefined function: Exquisite.Mixfile.application/0
    Exquisite.Mixfile.application()
    lib/exrm/deps.ex:176: anonymous fn/2 in ReleaseManager.Deps.get_applications/1
    (mix) lib/mix/project.ex:196: Mix.Project.in_project/4
    (elixir) lib/file.ex:1137: File.cd!/2
    (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1043: Enum.map/2
    lib/exrm/deps.ex:140: ReleaseManager.Deps.get_included_applications/1

The odd thing is when I revert back to my old copy it works fine.  My guess is there is something misconfigured in the Exquisite lib I am using but I am  not sure why the old version works and the new version fails.

Old Sha of exrm that works: 02b63f32ba1982338d216171cbc4a97523442523

**Comment by bitwalker** [comment] 2015-11-19 21:25
@cjimison I know what the problem is here, thanks for reporting! I'll get a fix up ASAP.

**Comment by bitwalker** [comment] 2015-11-19 21:33
@cjimison I pushed the fix for this as well as a new RC release (1.0.0-rc4).

**Closed** 2015-11-19 21:32 UTC
