### ISSUE TITLE
mix release produces strange errors

### ISSUE THREAD

**Issue by d-b** [bitwalker/exrm#134] opened 2015-06-18 01:12 UTC
db@vmbox ~/elixir/exrm/test/fixtures/example_app $ git rev-parse HEAD
08de5b500744833c0c97d91eb86d60f009c0346a

db@vmbox ~/elixir/exrm/test/fixtures/example_app $ elixir --version
Elixir 1.0.4

db@vmbox ~/elixir/exrm/test/fixtures/example_app $ mix release
==> Building release with MIX_ENV=dev.
==> Generating relx configuration...
==> Generating sys.config...
==> Generating boot script...
==> Conform: Loading schema...
==> Conform: Schema succesfully loaded!
==> Conform: Generating escript..
==> Conform: Adding overlays to relx.config...
==> Conform: Done!
==> Performing protocol consolidation...
==> Generating release...
/usr/bin/mix:2: syntax error before: '#'
/usr/bin/mix:2: syntax error before: '#'
/usr/bin/mix:2: syntax error before: '#'
/usr/bin/mix:2: syntax error before: '#'
/usr/bin/mix:2: syntax error before: '#'
/usr/bin/mix:2: syntax error before: '#'
/usr/bin/mix:2: syntax error before: '#'
/usr/bin/mix:2: syntax error before: '#'
/usr/bin/mix:2: syntax error before: '#'
==> Generating nodetool...
==> Packaging release...
==> The release for test-0.0.1 is ready!

**Comment by bitwalker** [comment] 2015-06-18 15:09
That is strange, it doesn't seem to affect the actual release at all, I wonder what's producing that error. Thanks for reporting!

**Comment by eproxus** [comment] 2015-06-22 08:48
I can reproduce with Elixir 1.0.4 and Mix 1.0.4. Running other Mix commands does not print the errors.

**Comment by janjiss** [comment] 2015-06-25 22:18
+1 from me, but I can't do a second release for some reason. Full trace:
```
The deploy has failed with an error: Exception while executing as root@elixirstream.com: mix exit status: 1
mix stdout: ==> Building release with MIX_ENV=prod.
==> Generating relx configuration...
==> Generating sys.config...
==> Generating boot script...
==> Conform: Loading schema...
==> Conform: No schema found, conform will not be packaged in this release!
==> Performing protocol consolidation...
==> Generating release...
/usr/local/bin/mix:2: syntax error before: '#'
/usr/local/bin/mix:2: syntax error before: '#'
/usr/local/bin/mix:2: syntax error before: '#'
/usr/local/bin/mix:2: syntax error before: '#'
/usr/local/bin/mix:2: syntax error before: '#'
/usr/local/bin/mix:2: syntax error before: '#'
/usr/local/bin/mix:2: syntax error before: '#'
/usr/local/bin/mix:2: syntax error before: '#'
/usr/local/bin/mix:2: syntax error before: '#'
==> Generating nodetool...
==> Packaging release...
mix stderr: ** (MatchError) no match of right hand side value: {:error, {:bad_file_type, '/var/www/elixirstreamphoenix/releases/20150625220438/rel/elixir_stream/tmp/erl_pipes/elixir_stream/erlang.pipe.1.r', :other}}
    lib/mix/tasks/release.ex:358: Mix.Tasks.Release.update_release_package/1
    lib/mix/tasks/release.ex:73: Mix.Tasks.Release.do_run/1
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:307: Code.require_file/2
```

**Comment by bitwalker** [comment] 2015-06-26 15:28
I can confirm this is happening when calling into `:relx.do`, but still unsure what could be causing it. I'm at a bit of a loss.

/cc @tsloughter

**Comment by tsloughter** [comment] 2015-06-26 15:29
Um, no idea :). It works fine but mix prints an error message?

**Comment by bitwalker** [comment] 2015-06-26 15:34
@tsloughter Yeah, the release builds just fine, but that error message is being printed every time. It's bizarre.

**Comment by tsloughter** [comment] 2015-06-26 15:36
I guess check if it happens on all mix/elixir versions and recent versions of relx or if only certain versions of mix cause it to happen on all relx...

**Comment by bitwalker** [comment] 2015-06-26 16:09
@tsloughter Here's what I'm seeing with verbose logging turned on (using the latest everything, other than OTP which is 17.5 on my system):

```
===> Provider successfully run: resolve_release
===> Running provider overlay
/Users/pschoenf/.exenv/versions/master/bin/mix:2: syntax error before: Mix
===> Provider successfully run: overlay
===> Running provider release
/Users/pschoenf/.exenv/versions/master/bin/mix:2: syntax error before: Mix
/Users/pschoenf/.exenv/versions/master/bin/mix:2: syntax error before: Mix
/Users/pschoenf/.exenv/versions/master/bin/mix:2: syntax error before: Mix
/Users/pschoenf/.exenv/versions/master/bin/mix:2: syntax error before: Mix
/Users/pschoenf/.exenv/versions/master/bin/mix:2: syntax error before: Mix
===> Including Erts from /usr/local/Cellar/erlang/17.5/lib/erlang
/Users/pschoenf/.exenv/versions/master/bin/mix:2: syntax error before: Mix
/Users/pschoenf/.exenv/versions/master/bin/mix:2: syntax error before: Mix
/Users/pschoenf/.exenv/versions/master/bin/mix:2: syntax error before: Mix
===> release successfully created!
```

Any clues there that might help me track this down? I'll keep poking around.

**Comment by tsloughter** [comment] 2015-06-26 16:16
No idea. I'd want to know if a change in relx or mix caused this to start happening first. And then to figure out what is trying to access the mix script besides that the user runs it.

**Comment by bitwalker** [comment] 2015-06-26 16:38
The commit which introduces this behavior is e884f9c. In my test scenario I've also overridden relx to 2.0.0 and conform to 0.13.0 (basically what they were before consuming relx as a library rather than as a bundled binary), so the only thing that has changed beyond that is the change to the `Utils` module. And what boggles my mind is that there is no call to mix whatsoever. I've got nothing :/.

**Comment by bitwalker** [comment] 2015-06-30 19:59
This is now fixed and pushed in release 0.17.3.

**Closed by bitwalker** 2015-06-30 19:59 UTC
Labels: in progress, third party issue

**Comment by eproxus** [comment] 2015-07-02 08:40
Just curious, what was the problem? :smile:

**Comment by bitwalker** [comment] 2015-07-02 14:44
@eproxus In relx, there was code which loaded templates for various bits by using `escript:extract(path, [compile_source])`. This function prints errors to stdout with no control over that behaviour. The `compile_source` flag turns out to be unnecessary in this case, and was the cause of the errors being printed.

**Comment by eproxus** [comment] 2015-07-02 15:04
Ah, interesting. Thanks!
