### ISSUE TITLE
deps and included_applications

### ISSUE THREAD

**Issue by cjimison** [bitwalker/exrm#172] opened 2015-07-22 00:03 UTC
Here is kind of an odd case that I was hoping for a bit of insight into:

- I have an umbrella project with 3 applications in it, lets call them App1, App2, and App3
- This umbrella project will create two different exrm release builds and they are App1 and App3.
  - App1 has an "include_appplications" list with App2
  - App3 has both App1 and App2 in it's applications list

My expectation would be when I run App1, App2 was not started.  And when I run App3 I should see both App1 and App2 running, however when App3 is started only App1 is running.

It looks like the "included_applications" list from App1 is overriding the fact that it should be started in App3.  I was hoping that since App3 is the "root" project anything in the "applications" list would override any "included_applications" from a dependency.

Is there any way to get around this behavior? 

Once again any help would be greatly appreciated!

**Comment by cjimison** [comment] 2015-07-22 00:05
As a followup:  If I run the projects using

iex -S mix

The behavior is what I was expecting:

App1 runs without App2
App3 runs with both App1 and App2 started

Thanks!

**Comment by bitwalker** [comment] 2015-07-23 14:31
The configuration is merged I believe, could you try adding `included_applications: []` to App3's mix.exs to see whether that fixes it? I'll try and dig in to this as soon as I can, just got back from vacation though and have a bit of a backlog :(

**Comment by cjimison** [comment] 2015-07-23 20:09
No joy, same behavior as before :p

-Chris

**Comment by bitwalker** [comment] 2015-08-12 18:39
@cjimison Could you post the mix.exs of each application? I want to try and reproduce this locally.

**Comment by cjimison** [comment] 2015-08-12 22:02
@bitwalker Sorry for the delay in response, I am out of town.  I created a sample project that should show the behavior off here:

https://github.com/cjimison/testExrm

Let me know if there is anything else I can do to help.

Thanks!

NOTE:  This is a quick and dirty project so please forgive any type-o, etc

**Comment by bitwalker** [comment] 2015-08-12 22:27
Found the cause of the issue in the Erlang docs [here](http://www.erlang.org/doc/design_principles/included_applications.html).

The gist of it is these points:

- An application can only be included by one other application.
- An included application can include other applications.
- An application that is not included by any other application is called a primary application.
- The application controller automatically loads any included applications when loading a primary application, but does not start them. Instead, the top supervisor of the included application must be started by a supervisor in the including application.
- **This means that when running, an included application is in fact part of the primary application, and a process in an included application considers itself belonging to the primary application.**

In effect, what this means is that because `alt` includes `util`, `alt` is responsible for starting/supervising `util`. I think what you really want here is for `util` to be started as a primary application, in which case it should be in `applications` for both `main` and `alt`.

**Comment by cjimison** [comment] 2015-08-13 00:17
Gotcha.  Learn something new about erlang every day :)

> In effect, what this means is that because alt includes util, alt is responsible for starting/supervising util. I think what you really want here is for util to be started as a primary application, in which case it should be in applications for both main and alt
> 
What I was hoping for was to include the code from “util” in the “alt” release package so I can call the Util.print function (which does a GenServer.cast to Utils.Server, a process registered in global).  Basically what we are looking to do is something like so:

Node 1)

main, alt, util

Node 2)

alt_app

Node N)

alt_app


with Nodes 2 - N including the “util" code in the release but NOT running the util supervisor/gen server.  If I made util the primary application it would start up it’s supervisor on all the nodes which is not what I want.

Just to give more context our project is games based so “util" in this case maybe a very large world map that is tracking player positions/etc and has a very high memory requirement (play positions change to quickly to be stored in a data base), alt is a TCP interface handler/msgPack serialize/deserializer which we will throw on hardware with less memory, and main could be a user Auth system.  When load is low we may just run Node 1 and when load starts to spike we will spin up Node 2+ (games tend to be VERY chatty so we burn a lot of CPU time just packing/unpack data).

Note: we have a work around for this in that we split our applications up into two types, logic applications which we do not build release packages, and deployment application that we use as primary and hand manage :applications and :included_applications in.  I was just hoping there was a way to cut this down because we have something like 5 different deployment packages and 15 logical packages.

Thanks for all the help!

- Chris

**Comment by bitwalker** [comment] 2015-08-13 04:15
@cjimison The context helps a lot, I made the changes to your testExrm app for what you would need to do and sent your repo a PR so you can see the diff, but just to clarify the setup:

- `alt` has `util` in it's `included_applications`
- `main` has `alt` in it's `applications`
- `main` is responsible for starting `util` in it's startup code (or wherever makes the most sense in order to ensure it's supervised)

This allows you to use `util` code in `alt`, without starting the `util` application, while also allowing `main` to pull in both `alt` and `util` and have the `util` application started. The non-intuitive bit here is that unlike most of the time when you omit an application in a release and it is not available at runtime, because `main` has `alt` in it's `applications`, and `alt` has `util` in it's `included_applications`, `util` is actually included in the release.

Hopefully that helps or at least makes sense. Let me know if you have any additional questions on this!

**Comment by cjimison** [comment] 2015-08-13 04:27
@bitwalker WOW this is awesome!!  Thank you so much for taking the time to dig into that project and updating it with the need changes.  That was really above and beyond what I was hoping for and I will be tasking some folks out tomorrow to help me clean our builds.

- Chris

**Closed** 2015-09-05 00:49 UTC
Labels: in progress, umbrella-projects
