### ISSUE TITLE
Error during release: "could not find app idna {1,0,0}"

### ISSUE THREAD

**Issue by drouchy** [bitwalker/exrm#66] opened 2014-10-01 08:21 UTC
Hi,

I'm trying the build a release for a project of mine, and I'm facing a odd problem:

```shell
MIX_ENV=staging mix release                                                                                                         <2.1.2> master [b997f51] modified untracked
==> Building release with MIX_ENV=staging.
==> Generating relx configuration...
==> Generating sys.config...
==> Generating boot script...
==> Performing protocol consolidation...
==> Conform: Loading schema...
==> Conform: No schema found, conform will not be packaged in this release!
==> Generating release...
==> Generated .appup for shutl_inspector 0.0.1 -> 0.0.2
===> Application metadata file exists but is malformed: /opt/boxen/exenv/versions/1.0.0/lib/mix/test/fixtures/deps_status/_build/dev/lib/invalidapp/ebin/invalidapp.app
===> Application metadata file exists but is malformed: /opt/boxen/exenv/versions/1.0.0/lib/mix/test/fixtures/deps_status/_build/dev/lib/invalidvsn/ebin/invalidvsn.app
===> Application metadata file exists but is malformed: /opt/boxen/exenv/versions/1.0.0/lib/mix/test/fixtures/deps_status/_build/dev/lib/ok/ebin/ok.app
could not find app idna {1,0,0}
```

I don't directly depend on idna, but on dependency of one of my dependencies depends on it. The odd part is if I look at the mix.lock file

```shell
 grep idna mix.lock
  "idna": {:package, "1.0.1"},
```

As you can see the idna version is 1.0.1 not 1.0.0

Cheers,

David

**Comment by olhado** [comment] 2015-03-09 17:30
Any updates on this or #92 ?

**Comment by bitwalker** [comment] 2015-03-09 18:01
I know what the issue is here, I need to implement a fix that keeps relx from discovering libs present under the `rel/` directory, I'm guessing this is a config issue on my end. I'll follow up once I can reproduce this.

**Comment by bitwalker** [comment] 2015-03-09 18:12
@olhado Are you able to reproduce this error? Could you either reproduce it using https://github.com/bitwalker/exrm-test or by pushing up a repo of a project in which this occurs? That will help me pinpoint this. It appears the issue I was thinking of has already been addressed in one of the previous fixes made, and I can't reproduce it.

**Comment by olhado** [comment] 2015-03-09 18:23
I haven't tried lately, been busy with other stuff. The repo I was able to replicate it on was:

https://github.com/olhado/infiniteroll

I was building and installing on an Amazon Linux micro instance.

You can build version 0.0.1 from: https://github.com/olhado/infiniteroll/commit/3fcb899fba2bd64f4e89dbc99b35b46b02005a72

And then take head and it will be set to go to 0.0.2 (with the dicer library update from 0.7.0 to 0.8.0)

**Comment by olhado** [comment] 2015-03-13 20:48
Were you able to reproduce with my example project?

**Comment by olhado** [comment] 2015-05-19 13:50
Just a friendly ping. I assume you have some leads (since other people have reported similar issues), but are crunched for time :)

**Comment by bitwalker** [comment] 2015-05-22 16:29
I'm sorry man, I'll take a look today!

**Comment by olhado** [comment] 2015-06-18 19:18
Ping! Did 0.17.0 potentially fix this?

**Comment by bitwalker** [comment] 2015-06-26 16:50
@olhado Seems to work, but there is another blocking issue for which I need @tsloughter's help:

It seems like relx expects all dependencies to have .appups? See the following from the log:

```
===> Provider (relup) failed with: {error,
                                           {rlx_prv_relup,
                                            {relup_script_generation_error,
                                             systools_relup,
                                             {file_problem,
                                              {"/Users/pschoenf/Repositories/infiniteroll/rel/infiniteroll/lib/dicer-0.8.0/ebin/dicer.appup",
                                               {error,
                                                {open,
                                                 "/Users/pschoenf/Repositories/infiniteroll/rel/infiniteroll/lib/dicer-0.8.0/ebin/dicer.appup",
                                                 enoent}}}}}}}
```

@tsloughter I would expect that if no appup is found for a child application, that it isn't a problem (doesn't seem to have been up until ~2.1.x). Is this a misconfiguration on exrm's part?

**Comment by tsloughter** [comment] 2015-06-26 16:50
There must be an appup if an app version changes.

**Comment by bitwalker** [comment] 2015-06-26 16:55
@tsloughter Makes perfect sense to me why, but that seems like it presents a serious problem for anyone using releases, since they have to provide an appup for all applications if not provided by the author of those applications. I haven't run into this error before, so I'm assuming this is a recent change, what's the best way to handle it?

**Comment by tsloughter** [comment] 2015-06-26 16:58
It is not a recent change. If it is now failing even when the app hasn't changed then that would be a recent bug added. But if the app did change and there is no appup then it should have always been failing.

This is why I don't have an appup generator in relx. The creation of appups should be in the app build tool (mix, rebar3, etc) because it should be done by all apps when a new version is created and stored in the package/repo. It is something I haven't yet integrated into rebar3 but plan to and want to get it to be standard practice.

**Comment by bitwalker** [comment] 2015-06-26 17:21
Well the problem here is that the app being released `infiniteroll` has an appup, one of it's dependencies `dicer` was updated between versions of `infiniteroll`, but the release is failing with the error seen above, as it appears to be looking for `dicers` appup, but that is an app out of control of the author of `infiniteroll`. This is the first time I've seen this issue reported, so either nobody is using upgrades (certainly possible) and this is the first time it's come up, or something is different. I guess I can work around it by going through all apps and generating appups where they are missing, but that seems dumb.

+1 to having an appup generator in the build tool itself though, I wish that were the case :(.

**Comment by olhado** [comment] 2015-07-21 02:49
The real issue is that `dicer` is more of a library than it's own app. Maybe I am including it wrong in my mix config for `infiniteroll`, but creating an appup for a library feels very wrong.

**Comment by bitwalker** [comment] 2015-08-12 18:33
This should be fixed as of 0.19.0 now. Could you test with it and let me know how it goes?

**Comment by olhado** [comment] 2015-08-19 02:40
Verified!

Sorry it took so long, real life and a hex.pm hiccup delayed verification.

**Comment by mweibel** [comment] 2015-08-25 05:36
@bitwalker just ran into this issue as well but with the dependency of a dependency. Upgraded to 0.19.0 and it successfully created an appup file for the dependency, however not of the dependency of a dependency. Trying to do something reproducable with exrm-test now..

**Comment by bitwalker** [comment] 2015-08-25 15:49
@mweibel Yeah I just got another bug report that nested deps weren't being picked up, so I've got that tracked as a bug. I'll be working on a fix after I finish some other work that is queued up, hopefully very soon :)

**Closed** 2015-09-05 17:00 UTC
Labels: question, third party issue
