### ISSUE TITLE
Error generating release

### ISSUE THREAD

**Issue by randysecrist** [bitwalker/exrm#106] opened 2015-03-03 17:55 UTC
I'm seeing this when I clone and build my own project as well as when I build the exrm-test project.  I'm using Elixir 1.0.2, and Erlang OTP 17.  It looks like a problem with relx, or how it is being used.  Anyone else bumped into this?

=ERROR REPORT==== 3-Mar-2015::10:50:31 ===
Error in process <0.32.0> with exit value: {function_clause,[{rlx_dscv_util,discover_dir,[#Fun<rlx_app_discovery.4.27708845>,<<16 bytes>>,undefined],[{file,"src/rlx_dscv_util.erl"},{line,81}]},{lists,map,2,[{file,"lists.erl"},{line,1237}]},{ec_plists,'-local_runmany/3-fun-0-',3,[{file,"src/ec_plists.erl"},{line,753}]}]}

escript: exception exit: {function_clause,
                    [{rlx_dscv_util,discover_dir,
                         [#Fun<rlx_app_discovery.4.27708845>,
                          <<"/Users/randy/lib">>,undefined],
                         [{file,"src/rlx_dscv_util.erl"},{line,81}]},
                     {lists,map,2,[{file,"lists.erl"},{line,1237}]},
                     {ec_plists,'-local_runmany/3-fun-0-',3,
                         [{file,"src/ec_plists.erl"},{line,753}]}]}
  in function  ec_plists:handle_error/3 (src/ec_plists.erl, line 900)
  in call from ec_plists:local_runmany/3 (src/ec_plists.erl, line 764)
  in call from rlx_dscv_util:do/2 (src/rlx_dscv_util.erl, line 52)
  in call from rlx_app_discovery:resolve_app_metadata/2 (src/rlx_app_discovery.erl, line 103)
  in call from rlx_prv_discover:do/1 (src/rlx_prv_discover.erl, line 46)
  in call from relx:run_provider/2 (src/relx.erl, line 280)
  in call from lists:foldl/3 (lists.erl, line 1261)
  in call from relx:run_providers/1 (src/relx.erl, line 268)

**Comment by bitwalker** [comment] 2015-03-03 18:04
@randysecrist What OS are you using when this occurs, and I assume you are using the latest version of exrm yes?

**Comment by randysecrist** [comment] 2015-03-03 20:12
I'm on OS X, 10.10.  For exrm, i've used 0.14.11 and tried 0.15.1.

Digging in more this afternoon to see if I can spot anything stupid I'm doing.

**Comment by randysecrist** [comment] 2015-03-03 20:14
Hmm,

So if I create a $HOME/lib directory, I then see this new error.

===> Missing beam file elf_format <<"/Users/randy/.erln8.d/otps/r1731/dist/lib/erlang/lib/hipe-3.11.1/ebin/elf_format.beam">>

Failed to solve release:
 Dependency iex is specified as a dependency but is not reachable by the system.

**Comment by bitwalker** [comment] 2015-03-05 17:23
Could you run `mix release --verbosity=verbose` and gist the output? That should help me track down what the cause may be. It seems to me that it's unable to find the Elixir lib directory for some reason, but I would expect other problems to present themselves, but it could be an edge case in exrm which produces an incorrect path to that directory.

**Comment by randysecrist** [comment] 2015-03-07 01:37
Sure thing.

https://gist.github.com/randysecrist/805dc5b5b0191b2d9513

**Comment by bitwalker** [comment] 2015-03-09 17:50
Yeah it's resolving Erlang just fine, but Elixir is not being found properly, I'm almost certain that's why it's adding `/Users/randy/lib` to the resolution path. I think it may be failing to look up the Elixir lib path properly. Could you run `iex`, and enter the following, and then paste the output? 

```elixir
> path = System.find_executable("elixir")
<some path>
> case path |> String.to_char_list |> :file.read_link_info do
      {:ok, {:file_info, _, :regular, _, _, _, _, _, _, _, _, _, _, _}} ->
        {:regular, path}
      {:ok, {:file_info, _, :symlink, _, _, _, _, _, _, _, _, _, _, _}} ->
        {:ok, sym} = path |> String.to_char_list |> :file.read_link
        case sym |> :filename.pathtype do
          :absolute ->
            {:abs_symlink, sym |> IO.iodata_to_binary}
          :relative ->
            symlink = sym |> IO.iodata_to_binary
            {:rel_symlink, symlink, path |> Path.dirname |> Path.join(symlink) |> Path.expand}
        end
    end
```
That should tell me all I need to know about what's potentially happening here.

**Comment by randysecrist** [comment] 2015-03-10 02:41
Yep!  Here you go:

https://gist.github.com/randysecrist/805dc5b5b0191b2d9513#file-where_is_elixir-txt

I have elixir cloned and built in my $HOME/bin dir.

**Comment by bitwalker** [comment] 2015-03-11 18:30
@randysecrist I found the bug, because some code if have uses `String.replace` to remove the `/bin/elixir` path part from the end (in order to get the Elixir HOME directory), and your Elixir happens to be installed to `$HOME/bin/elixir`, what's happening is it's turning `$HOME/bin/elixir/bin/elixir` into `$HOME`. If you were to move your Elixir install just about anywhere else, it would work. I'm going to fix that issue right now though, so this will be fixed in master shortly.

**Closed** 2015-03-11 18:46 UTC

**Comment by bitwalker** [comment] 2015-03-11 18:47
Pushed as part of the 0.15.3 release.

**Comment by randysecrist** [comment] 2015-03-12 23:44
Awesome!  "The release for test-0.0.1 is ready!"

Thanks for digging in.  Will you be at erlang factory this month?

**Comment by bitwalker** [comment] 2015-03-13 15:24
@randysecrist Glad to hear that solved it for you :). And as for Erlang Factory, I was initially planning on going, but it just so happens that I'm visiting my fiancé for a couple weeks starting next Friday, so I'm having to miss out :(. I will be at the next ElixirConf in the states though, which is happening this October, I wish I could've made the one in Poland, but travel gets expensive pretty fast haha.

**Comment by sevos** [comment] 2015-04-19 10:59
Hey, I am using version 0.15.3 and the problem occured for me again.

https://gist.github.com/sevos/d7f7d10af7220a7d23b3

any ideas? ;)

**Comment by sevos** [comment] 2015-04-19 14:03
FYI: upgrading elixir to 1.0.4 (from 1.0.3), puring rel and _build dirs, mix deps.clean --all and then starting from scratch fixed the problem

**Comment by bitwalker** [comment] 2015-04-20 15:40
@sevos Thanks for the report, I'll keep an eye on this, I have some thoughts on what might be causing this but I haven't been able to reliably reproduce it yet.

**Comment by sevos** [comment] 2015-04-20 16:00
Also, I could reproduce it when trying to do make release (subsequent release) when release was started in the background. I solved it by extracting release to another directory and running it from there.

This might've been problem in the first place, when upgrading elixir fixed it (I think that Erlang also upgraded at the time, thus VM got restarted).
