### ISSUE TITLE
Deploy to Ubuntu Dockerfile

### ISSUE THREAD

**Issue by expelledboy** [bitwalker/exrm#96] opened 2015-01-14 19:08 UTC
Hi 

Does the ./bin/app script work on Ubuntu? I am trying to deploy this in a Docker container (trenpixster/elixir:1.0.2), but I get the following set of errors:

```
root@288fbff23591:/opt/portal# ./bin/portal start
/opt/portal/erts-6.2.1/bin/run_erl: 1: /opt/portal/erts-6.2.1/bin/run_erl: Syntax error: Unterminated quoted string
```

```
root@288fbff23591:/opt/portal# ./bin/portal foreground
Exec: /opt/portal/erts-6.2.1/bin/erlexec -noshell -noinput +Bd -boot /opt/portal/releases/0.0.1/portal -mode embedded -config /opt/portal/releases/0.0.1/sys.config -boot_var ERTS_LIB_DIR /opt/portal/erts-6.2.1/../lib -args_file /opt/portal/releases/0.0.1/vm.args -- foreground
Root: /opt/portal
/opt/portal/erts-6.2.1/bin/erlexec: 1: /opt/portal/erts-6.2.1/bin/erlexec: Syntax error: word unexpected (expecting ")")
```

**Comment by bitwalker** [comment] 2015-01-16 18:40
It definitely should, so I expect something was likely changed to break it. What version of Ubuntu specifically are you deploying to? I can set up a VM and do some digging.

**Comment by sperant** [comment] 2015-02-01 17:51
I ran into this exact same issue on Ubuntu 14.04.

**Comment by rcdilorenzo** [comment] 2015-02-07 18:52
Yes, same here.

**Comment by rcdilorenzo** [comment] 2015-02-07 20:11
I actually tried this on a Debian install and had the same problem as on the Ubuntu install. However, I was able to resolve it by compiling the release on a Debian OS, but that obviously negates a lot of the reasons for `exrm`, meaning that it's a temporary fix.

**Comment by bitwalker** [comment] 2015-02-09 18:18
@rcdilorenzo It's necessary to build the release on the target platform, that's unavoidable, since the binaries generated are compiled for that specific platform. It should work if the platforms are similar enough (for instance, I'd expect that a release compiled on Debian *should* work on Ubuntu, but it's not a guarantee). Is this the issue you are running into, or are you seeing the same error even when compiling on the target platform?

**Comment by rcdilorenzo** [comment] 2015-02-09 18:47
Compiling on the target system worked properly, eliminating this error @expelledboy mentioned.

**Comment by bitwalker** [comment] 2015-02-09 18:58
@expelledboy Is this the cause of your issue as well? Were you compiling on a different platform/architecture than your target system?

**Comment by bitwalker** [comment] 2015-02-11 08:08
@rcdilorenzo I just merged a PR that adds support for cross-compiling releases. See #99.

**Comment by rcdilorenzo** [comment] 2015-02-11 14:51
Excellent!

**Closed** 2015-07-03 06:57 UTC
Labels: bug, deployment/operating-system
