### ISSUE TITLE
Clarify config generation

### ISSUE THREAD

**Issue by manukall** [bitwalker/exrm#194] opened 2015-09-02 07:37 UTC
Hi bitwalker,
i hope it's ok to ask this here:

how do i change a config value after deployment? it seams only new keys in the my_app.conf are picked up, while existing ones keep their old value. is there any other way than manually changing running-conf?

my workflow now is the following: i'm using https://github.com/HashNuke/ansible-elixir-stack for deployment. so i have a release running under /srv/apps/my_app and the source code is at /home/deployer/my_app. 
when i deploy a new version, /home/deployer/my_app is updated from git, a new release is generated and copied to /srv/apps/my_app. from there i run the upgrade command.
what i'd like now is for changes i make to the config under git control to be reflected in my app after upgrading. is that possible?

sorry for the probably confusing wall of text. i'm kind of lost...

**Comment by bitwalker** [comment] 2015-09-02 14:34
That does seem like a bug to me if the new .conf is not being merged properly. I'll do some digging. Can you provide me with an example configuration change? It doesn't have to be exact, but I'd like to get an idea of what the previous versions .conf was like vs. the new one.

**Comment by manukall** [comment] 2015-09-02 18:46
thanks for the quick reply. here is what i'm trying to do:

in the example_app inside test/fixtures:
1. `mix release`
2. `rel/test/bin/test console`
    `Application.get_env(:test, :foo)` -> "bar"
3. change value of test.foo to "not_bar" in config/test.conf
4. `mix release`
5. `rel/test/bin/test console`
    `Application.get_env(:test, :foo) -> "bar"`

is it intended behavior that 5. still returns "bar"? i was hoping that after the changes in 3. it would return "not_bar".

it's not clear to me which settings from which files take precedence and when the running config is updated though.

**Comment by lsandeep83** [comment] 2015-09-03 03:13
I had similar issue as well in deploying my phoenix application with EXRM. 

Note: `prod.exs` is imported into `config.exs`

# Details

`v0.0.3: config/prod.exs`
```elixir
config :icing, Icing.Endpoint,
  url: [host: "example.com"]
```

`v0.0.4: config/prod.exs` 
```elixir
config :icing, Icing.Endpoint,
  url: [host: "geticing.com"]
```

The changes are **NOT** reflected in `/running-config/sys.config`. They are however reflected  in `/releases/0.0.4/sys.config`.

# Fix

I had to update the changes manually into `/running-config/sys.config` and the create another release with `mix release`

# Possible Causes
Is this possible related to #192 ? #192 has not been merged in to the latest hex package.

**Comment by bitwalker** [comment] 2015-09-03 15:53
@manukall @lsandeep83 Thanks for providing some details for me, I'll get this sorted out today.

It's not related to #192, as that syntax bug fixed an issue with copying the `.conf` file (assuming you have one), but not `sys.config`.

**Closed** 2015-09-03 17:14 UTC
Labels: bug, configuration

**Comment by bitwalker** [comment] 2015-09-03 17:19
Hey guys, I've fixed this issue, there was both a bug and a deliberate choice made, so I just want to clarify why the old behaviour was there (I luckily left a comment for my future self).

I had set things up based on the assumption that in production the configuration could be modified in-situ, and if we blindly applied the config from the release package, it could blow away those configuration settings, and during a hot upgrade/downgrade that may not be desirable. So I made the deliberate choice to leave it up to the deployer to choose whether to apply that config manually. There was however a bug where when not using conform, the running config was copied over the config in the release package, which obviously is no good.

I've changed it now so that the release config is always applied on upgrade/downgrade, however it also preserves the last running sys.config/app.conf file so that they can be referred to in case modifications were made. I can see how both situations would be annoying (1. applying an upgrade and having your config swapped out underneath you when you don't want that, and 2. expecting the new config to always be updated and not having that happen). I'm not sure which default behaviour is best honestly, but I'm defaulting to always updating the config, since that seems to be the more common scenario in practice.

**Comment by bitwalker** [comment] 2015-09-03 17:20
This fix is released in 0.19.3 by the way.

**Comment by manukall** [comment] 2015-09-04 12:58
thanks @bitwalker. i've updated to and already deployed with 0.19.3

**Comment by lsandeep83** [comment] 2015-09-07 06:36
Thanks @bitwalker. Updating the config is probably a more common scenario.

**Comment by joshuap** [comment] 2015-10-08 23:07
@bitwalker this issue got me, too. My problem may be a bit different; we are currently deploying from *rel/* without doing hot upgrades (which HashNuke/ansible-elixir-stack has an option for, although we are rolling our own scripts). Basically what we do:

```sh
git pull origin master
mix deps.get
mix release.clean
mix release
rel/logplex/bin/logplex restart
```

My problem is that everything under *rel/logplex/running-config/* never gets updated. Is there a solution to that?

**Comment by bitwalker** [comment] 2015-10-09 01:02
@joshuap Are you using conform?

**Comment by joshuap** [comment] 2015-10-09 01:42
@bitwalker no I'm not; I'm just setting values in *config/config.exs*. Is conform required?

**Comment by joshuap** [comment] 2015-10-09 01:43
We also have a custom *rel/vm.args` file.

**Comment by bitwalker** [comment] 2015-10-09 02:37
@joshuap Not at all, I had just merged a fix for a bug similar to this for conform. I'll do some testing tomorrow and see if I can reproduce.

**Comment by joshuap** [comment] 2015-10-09 05:35
Cool, thanks! Let me know if there's anything I can do to help.

**Comment by bitwalker** [comment] 2015-10-09 16:13
@joshuap I've pushed a fix for this to master

**Comment by sumerman** [comment] 2016-01-11 18:01
This a00690a715ea400ec822b95171fc90da9356ae23 just silently broke my deployment. How to make `sys.config` persistent then? You say that new behaviour is a "default", actually there is only this behaviour without a way to change it. @bitwalker have ever heard about backwards compatibility and other people relying on a certain behaviour?

**Comment by bitwalker** [comment] 2016-01-11 23:50
@sumerman I'm sorry you got bit by the change, the hostility is unnecessary though - perhaps you missed that this change was made prior to 0.19.7 - a pre-1.0 release, and according to semantic versioning rules: "Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable". Regardless, I've tried my best to not break things with minor version increments to the best of my ability.

Now, as far as how to handle configuration:

1. You should not put environment/machine specific configuration in `config.exs` / `sys.config` when using releases. This configuration should be able to be upgraded as part of the release without breaking things. The reason for this is twofold: Firstly, the application configuration is updated by the release handler during the upgrade, so if your configuration has changed in the new version (new values, renamed values, etc.), the updated `sys.config` needs to be available. Secondly, your application being upgraded is still running - if it depends on the new configuration and it has not yet been loaded, it is very likely that your app will crash, or worse, continue running as if everything is fine, but be doing the wrong thing.
2. So in order to handle environment/machine specific configuration, you should provide these via environment variables. For instance, Phoenix applications typically configure the port to bind to via the `PORT` environment variable, and `config.exs` simply tells Phoenix to read this variable at runtime via the `{:system, "PORT"}` config value. This is a convention within Phoenix (`{:system, "PORT"}` doesn't do anything special in and of itself), but it's one I agree with and use myself in my own applications.

Your `sys.config` will be preserved during an upgrade however (it should be placed alongside the new one with a suffix), so you can (if desired) copy the old config over the new one, but you will also need to parse the config and apply it to the running application with `Application.put_env`. I would strongly recommend not doing this.

**Comment by sumerman** [comment] 2016-01-12 00:24
@bitwalker I'm so angry/hostile because you've assumed a use case and left no way to use the old behaviour. Furthermore, the new behaviour is quite surprising and is not articulated clearly in the documentation, at the time of writing it still states:
>The configs placed in `$DEPLOY_DIR/releases/$RELEASE_VER` will be used as persistent default configs. They will be used by first release start and placed in `$DEPLOY_DIR/releases/$RELEASE_VER/running-config` if no `RELEASE_MUTABLE_DIR` defined

1. Not everybody use release upgrades (in my experience very few do actually). A lot of people use releases as a convenient way to package their apps.
2. In my case configuration is placed into a file by chef, putting stuff into environment variables means a lot of boilerplate just to work around this new behaviour.

I would like to ask you to make this optional or, at the very least, provide an option to use `rel/sys.config` as is, without merging it with `config.exs`, so people can use "include" feature of `sys.config`.

**Comment by sumerman** [comment] 2016-01-12 01:29
For now I've found a workaround: I put the environment specific configuration into a separate file and add additional `-config my_app.config` line to the `vm.args`.

**Comment by bitwalker** [comment] 2016-01-12 01:56
@sumerman I understand the frustration, I hope you'll understand that these changes are motivated by more than just myself, and the problems this change solved were critical for those who are using hot upgrades. It's unfortunate that this change broke things for you, however that's why I hadn't pushed a v1 yet: there are a lot of moving pieces that had to be ironed out before I could be confident with stabilizing the API.  It is always possible to use the version of exrm you were using previously if the current version is causing you immediate problems.

Thanks for posting your solution though and letting me know that the documentation had some errors. I'll update the docs ASAP. Your solution is something I'll document as well, as it will be my recommendation for this use case moving forward.

Given that there is an available, non-hackish, workaround for your use case, I'm going to maintain the current behaviour unless a more clear need is identified.

**Comment by aaronjensen** [comment] 2016-01-16 03:32
A related issue we just ran into: We use conform as well as config.exs. We use config.exs for things that don't change on a per env basis and conform for things that do. If we:

1. Deploy an initial release
2. Build and deploy a second release
3. Stop the app
4. Start the app

**Comment by aaronjensen** [comment] 2016-01-16 03:37
Looking at the code in `boot`, I think I see what's happening. If you use conform, it applies the new conform file on top of the `running-config` if it is there, otherwise it uses the release config dir. What I don't understand is that it seems like this should only happen if we're using `RELEASE_MUTABLE_DIR` and I can't find anything that is using it. Our `running-config` always ends up in the base dir along side `releases`, not in the release dir. We use edeliver, so maybe they're doing that somehow?

**Comment by bitwalker** [comment] 2016-01-19 18:29
@aaronjensen Agreed, from what you've described I would expect it to reference the `sys.config` from the release directory in that case, not the one in `running-config`.

**Comment by aaronjensen** [comment] 2016-01-19 21:18
@bitwalker :+1: I added a new issue: #278
