### ISSUE TITLE
disable hipe compilation

### ISSUE THREAD

**Issue by igalic** [bitwalker/exrm#229] opened 2015-10-30 11:42 UTC
I'd like to explicitly disable hipe compilation.
i've added a rel/vm.args file with `--disable-hipe` but that didn't do anything…

see also: https://github.com/erlware/relx/issues/405

**Comment by bitwalker** [comment] 2015-11-12 17:24
I'm closing this for now, since the issue is that you need to compile your application with `--disable-hipe`, rather than provide it to the release as an argument.

**Closed by bitwalker** 2015-11-12 17:24 UTC
Labels: question
